// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDed1dX8F2TpTG3NbLugoTdJAEfoZ9f2Bo',
    appId: '1:591091586203:web:880d3fcbbdcce39e3de23e',
    messagingSenderId: '591091586203',
    projectId: 'hear-me-4ea80',
    authDomain: 'hear-me-4ea80.firebaseapp.com',
    storageBucket: 'hear-me-4ea80.firebasestorage.app',
    measurementId: 'G-5WHWKBHPXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrx9sXc0Wc78TGYsgAZhMbrgD6XAe_KnA',
    appId: '1:591091586203:android:26f1666d31ccfd8f3de23e',
    messagingSenderId: '591091586203',
    projectId: 'hear-me-4ea80',
    storageBucket: 'hear-me-4ea80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYYaOL136ix8Ma3HBWaKCCmkWjnH8Rec',
    appId: '1:591091586203:ios:fee883122f41211c3de23e',
    messagingSenderId: '591091586203',
    projectId: 'hear-me-4ea80',
    storageBucket: 'hear-me-4ea80.firebasestorage.app',
    iosBundleId: 'com.example.hearMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYYaOL136ix8Ma3HBWaKCCmkWjnH8Rec',
    appId: '1:591091586203:ios:fee883122f41211c3de23e',
    messagingSenderId: '591091586203',
    projectId: 'hear-me-4ea80',
    storageBucket: 'hear-me-4ea80.firebasestorage.app',
    iosBundleId: 'com.example.hearMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDed1dX8F2TpTG3NbLugoTdJAEfoZ9f2Bo',
    appId: '1:591091586203:web:1eb060e2cc23a9673de23e',
    messagingSenderId: '591091586203',
    projectId: 'hear-me-4ea80',
    authDomain: 'hear-me-4ea80.firebaseapp.com',
    storageBucket: 'hear-me-4ea80.firebasestorage.app',
    measurementId: 'G-FMYC4D2RRD',
  );
}
